version: '3'

services:
  webapp:
    build:
      context: ./install/bun
      dockerfile: Dockerfile
    init: true
    ulimits:
      memlock: -1
    ports:
      - "8080:8080"
    volumes:
      - ./code:/home/bun/app
    command: ["bun", "index.js"]
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=mydb
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
