# Use the base image "oven/bun:1.0"
FROM oven/bun:latest

# Install required packages
RUN bun install pg elysia

# Specify the default command to be run when the container starts
CMD ["/usr/local/bin/bun"]